alias: "Tänd fönsterlampor kväll"
initial_state: true
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 4
action: 
  service: light.turn_on
  entity_id:
   - light.all_windows