alias: "Släck Fönsterlampor Vardag o Sön"
initial_state: true
trigger:
  platform: template
  value_template: >
    {{ is_state('sensor.time',
       '22:45' if is_state('calendar.ledighet', 'off') else '01:00') }}

  #platform: time
  #at: "22:45:00"
  #at: "{% if is_state('calendar.ledighet', 'off') %}22:45:00{% else %}01:00:00{% endif %}"
condition:
  condition: and
  conditions:
   - condition: time
     weekday:
     - mon
     - tue
     - wed
     - thu
     - sun
   #- condition: state
   #  entity_id: calendar.ledighet
   #  state: 'off'
action:
  service: light.turn_off
  entity_id: 
   - light.all_windows

