alias: "Tänd Fönster Morgon"
initial_state: true
trigger:
  platform: template
  value_template: >
    {{ is_state('sensor.time',
       '05:15' if is_state('calendar.barnvecka', 'off') else '05:50') }}

  #platform: time
  #at: '05:15:00'
  #at: "{% if is_state('calender.barnvecka', 'off') %}05:15:00{% else %}05:50:00{% endif %}"
condition:
  condition: and
  conditions:
   - condition: state
     entity_id: calendar.ledighet
     state: 'off'
  # - condition: state
  #   entity_id: calendar.barnvecka
  #   state: 'off'
   - condition: time
     weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
action: 
  service: light.turn_on
  entity_id: 
    - light.all_windows
  data:
     transition: 120
     brightness_pct: 60 