alias: "Turn on Kökshall light "
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor
  to: 'on'
action:
  service: homeassistant.turn_on
  entity_id:  light.tvattstuga
  data_template:
    transition: 2
    brightness_pct: >
       {% if (now().hour >= 00) and (now().hour <= 05) %}10{% else %}100{% endif %}
