alias: "Turn on bathroom light "
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.presence_29
  to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_28
    below: 400
action:
  service: homeassistant.turn_on
  entity_id: light.spegel
  data_template:
    transition: 2
    brightness_pct: >
       {% if (now().hour >= 00) and (now().hour <= 05) %}5{% else %}100{% endif %}
