alias: "Turn off bathroom light 2 minutes after last movement"
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.badrummet
  to: 'off'
  for:
    minutes: 1
condition:
  - condition: state
    entity_id: binary_sensor.badrummet
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.spegel
    data:
      transition: 5
      brightness_pct: 5
#         {% if (now().hour >= 00) and (now().hour <= 05) %}5{% else %}50{% endif %}
  - delay: '00:01:00'
  - service: light.turn_off
    entity_id: light.spegel
    data:
      transition: 5
      