alias: "Släck Kökshallen Tak efter 1 minut"
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.kokshallen
  to: 'off'
  for:
    minutes: 1
condition:
  - condition: state
    entity_id: binary_sensor.kokshallen
    state: 'off'
action:
  - service: homeassistant.turn_on
    entity_id: light.takhh
    data:
      transition: 5
      brightness_pct: 50
  - delay: '00:00:30'
  - service: homeassistant.turn_off
    entity_id: light.takhh
    data:
      transition: 5
      