alias: "Släck Kökshallen Tak efter 1 minut"
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor
  to: 'off'
  for:
    minutes: 2
action:
  - service: homeassistant.turn_on
    entity_id:  light.tvattstuga
    data:
      transition: 5
      brightness_pct: 50
  - delay: '00:01:00'
  - service: homeassistant.turn_off
    entity_id: light.tvattstuga
    data:
      transition: 5
      