alias: "Turn on bathroom light "
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.badrummet
  to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.badrummet
    below: 400
action:
  service: light.turn_on
  entity_id: light.spegel
  data_template:
    transition: 2
    brightness_pct: >
       {% if (now().hour >= 00) and (now().hour <= 05) %}5{% else %}100{% endif %}
