alias: "BV Släck fönster barnrum helg"
initial_state: true
trigger:
  platform: time
  at: "22:45:00"
condition:
  condition: and
  conditions:
   - condition: state
     entity_id: calendar.barnvecka
     state: 'on'
   - condition: time
     weekday:
       - fri
       - sat
action:
  service: light.turn_off
  entity_id: 
   - light.linus_fh
   - light.ellas_fh