alias: "Starta motorvärmare BF"
initial_state: true
trigger:
  platform: time
  at: "05:30:00"
condition:
  condition: and
  conditions:
   - condition: state
     entity_id: calendar.barnvecka
     state: 'off'
   - condition: state
     entity_id: calendar.ledighet
     state: 'off'
   - condition: numeric_state
     entity_id: sensor.151_temperature
     below: '10'
   - condition: time
     weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
   - service: switch.turn_on
     entity_id: 
      - switch.pexen_heater
   - service: notify.html5
     data_template:
       message: "Motorvärmaren startad"