alias: "Släck utebelysning relä"
initial_state: false
trigger:
  platform: state
  entity_id: switch.skymningssensor_ute
  to: 'off'
action: 
  service: light.turn_off
  entity_id: 
   - light.outdoors