alias: "Släck utebelysning dag"
initial_state: true
trigger:
#  platform: time
#  at: "07:00:00"
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  above: 3.5
action:
  service: light.turn_off
  entity_id: 
   - light.outdoors