alias: "Slå av värme"
initial_state: true
trigger:
  platform: template
  value_template: >
    {{ is_state('sensor.time',
       '06:30' if is_state('calendar.barnvecka', 'off') else '07:30') }}

  #platform: time
  #at: '06:30:00'
  #at: "{% if is_state('calender.barnvecka', 'off') %}06:30:00{% else %}07:30:00{% endif %}"
condition:
  condition: and
  conditions:
   - condition: state
     entity_id: switch.heatpump 
     state: 'on'
   - condition: state
     entity_id: calendar.ledighet
     state: 'off'
   #- condition: state
   #  entity_id: calendar.barnvecka
   #  state: 'off'
   - condition: time
     weekday:
     - mon
     - tue
     - wed
     - thu
     - fri
action: 
  service: switch.turn_off
  entity_id: 
   - switch.heatpump