alias: "Slå på värme morgon"
initial_state: true
trigger:
  platform: template
  value_template: >
    {{ is_state('sensor.time',
       '04:00' if is_state('calendar.barnvecka', 'off') else '04:45') }}

 # platform: time
 # at: '04:00:00'
 # value_template: "{{ if is_state('calender.barnvecka', 'off') %}04:00:00{% else %}04:45:00{% endif }}"
condition:
  condition: and
  conditions:
   - condition: numeric_state
     entity_id: sensor.medeltemp_markplan
     below: '22.5'
   - condition: state
     entity_id: calendar.ledighet
     state: 'off'
#   - condition: state
#     entity_id: calendar.barnvecka
#     state: 'off'
   - condition: time
     weekday:
     - mon
     - tue
     - wed
     - thu
     - fri
action: 
  service: switch.turn_on
  entity_id: 
   - switch.heatpump