alias: "Stoppa Cirkulationspump Element"
initial_state: true
trigger:
   platform: state
   entity_id: switch.heatpump
   to: 'off'
   for:
    hours: 0
    minutes: 5
    seconds: 0
action: 
  service: switch.turn_off
  entity_id: 
   #- switch.cirkpump_radiator
    - switch.sonoffs2004